#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ValidationField {
  Name,
  Version,
  Description,
  Keywords,
  Homepage,
  Bugs,
  License,
  Author,
  Contributors,
  Maintainers,
  Files,
  Main,
  Type,
  Types,
  Typings,
  PackageManager,
  PublishConfig,
  Bin,
  Man,
  Directories,
  Repository,
  Module,
  Readme,
  Private,
  Engines,
  EngineStrict,
  Os,
  Cpu,
  Scripts,
  Dependencies,
  DevDependencies,
  OptionalDependencies,
  PeerDependencies,
}

impl ValidationField {
  pub const fn json_key(self) -> &'static str {
    match self {
      ValidationField::Name => "name",
      ValidationField::Version => "version",
      ValidationField::Description => "description",
      ValidationField::Keywords => "keywords",
      ValidationField::Homepage => "homepage",
      ValidationField::Bugs => "bugs",
      ValidationField::License => "license",
      ValidationField::Author => "author",
      ValidationField::Contributors => "contributors",
      ValidationField::Maintainers => "maintainers",
      ValidationField::Files => "files",
      ValidationField::Main => "main",
      ValidationField::Type => "type",
      ValidationField::Types => "types",
      ValidationField::Typings => "typings",
      ValidationField::PackageManager => "packageManager",
      ValidationField::PublishConfig => "publishConfig",
      ValidationField::Bin => "bin",
      ValidationField::Man => "man",
      ValidationField::Directories => "directories",
      ValidationField::Repository => "repository",
      ValidationField::Module => "module",
      ValidationField::Readme => "readme",
      ValidationField::Private => "private",
      ValidationField::Engines => "engines",
      ValidationField::EngineStrict => "engineStrict",
      ValidationField::Os => "os",
      ValidationField::Cpu => "cpu",
      ValidationField::Scripts => "scripts",
      ValidationField::Dependencies => "dependencies",
      ValidationField::DevDependencies => "devDependencies",
      ValidationField::OptionalDependencies => "optionalDependencies",
      ValidationField::PeerDependencies => "peerDependencies",
    }
  }
}
